export const STACK = [
	{
		name: "Typescript",
		logo: "typescript.svg",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
	},
	{
		name: "C#",
		logo: "csharp.svg",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
	},
	{
		name: "NodeJS",
		logo: "nodejs.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
	},
	{
		name: "Java",
		logo: "java.svg",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
	},
	{
		name: "Python",
		logo: "python.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
	},
	{
		name: "Swift",
		logo: "swift.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
	},
	{
		name: "CoffeeScript",
		logo: "coffeescript.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
	},
	{
		name: "CSS",
		logo: "css.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
	},
	{
		name: "HTML",
		logo: "html.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
	},
	{
		name: "Docker",
		logo: "docker.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
	},
	{
		name: "Github",
		logo: "github.png",
		href: "https://github.com/sponsors/loom4k",
		hoverColor: "hover:bg-pastel-pink",
	},
	{
		name: "Unity Engine",
		logo: "unity.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
	},
	{
		name: "GNU/Linux",
		logo: "linux.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
	},
	{
		name: "Tensorflow ML",
		logo: "tensorflow.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
	},
	{
		name: "Git VCS",
		logo: "git.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
	},
	{
		name: "Tailwind CSS",
		logo: "tailwind.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
	},
	{
		name: "Next.js",
		logo: "nextjs.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
	},
	{
		name: "React",
		logo: "react.png",
		href: "",
		hoverColor: "hover:bg-epic-black-light",
	},
];
